### ISSUE TITLE
'cancel' not working in Luks (and maybe lvm) submenu after first level

### ISSUE THREAD

**Issue by oberon-manjaro** [oberon-manjaro/manjaro-architect#3]

**Comment by oberon-manjaro** [comment]
Is this working now @Chrysostomus ? If not, maybe can we just use more loopmenu type functions?

**Comment by Chrysostomus** [comment]
I can't test it anymore today. I'll check when I can.

**Comment by oberon-manjaro** [comment]
which menu exactly is it we are talking about?

**Comment by oberon-manjaro** [comment]
this one?
```
luks_menu() {
    LUKS_OPT=""

    DIALOG " $_PrepLUKS " --menu "$_LuksMenuBody$_LuksMenuBody2$_LuksMenuBody3" 0 0 4 \
      "$_LuksOpen" "cryptsetup open --type luks" \
      "$_LuksEncrypt" "cryptsetup -q luksFormat" \
      "$_LuksEncryptAdv" "cryptsetup -q -s -c luksFormat" \
      "$_Back" "-" 2>${ANSWER}

    case $(cat ${ANSWER}) in
        "$_LuksOpen") luks_open
            ;;
        "$_LuksEncrypt")  luks_setup
            luks_default
            luks_show
            ;;
            "$_LuksEncryptAdv") luks_setup
            luks_key_define
            luks_show
            ;;
        *) return 0
            ;;
    esac
}
```

**Comment by oberon-manjaro** [comment]
So what is (or was) not working would be
main_menu() > prep_menu() > luks_menu()
and from there back to prep_menu() with cancel?

**Comment by oberon-manjaro** [comment]
No, I see now. One level down from there. It's not working, yet.

**Comment by oberon-manjaro** [comment]
I think the reason is simple:
We have
```
# Enter name of the Luks partition and get password to open it
    DIALOG " $_LuksOpen " --inputbox "$_LuksOpenBody" 10 50 "cryptroot" 2>${ANSWER} || return 0
    LUKS_ROOT_NAME=$(cat ${ANSWER})
    luks_password
```
so ``luks_password`` gets executed in any case.
I think we need:
```
DIALOG ... || return 0
if [[ $? -eq 0 ]]; then
     luks_password
fi
```

**Comment by oberon-manjaro** [comment]
no. my bad. Concel in that first subsub-menu is working already anyway ;)
The other ones are not ok somehow...

**Comment by oberon-manjaro** [comment]
I think now I understand:
```
case $(cat ${ANSWER}) in
        "$_LuksOpen") luks_open
            ;;
        "$_LuksEncrypt")  luks_setup
            luks_default
            luks_show
            ;;
            "$_LuksEncryptAdv") luks_setup
            luks_key_define
            luks_show
            ;;
        *) return 0
            ;;
    esac
```
When you ``return 0`` inside ``luks_setup()`` you do exit luks_setup(), but we do not leave ``luks_menu()``! It continues and executes ``luks_key_define()`` next!

**Comment by oberon-manjaro** [comment]
chain the functions conditionally like this in luks_menu()?
``luks_setup && luks_key_define && luks_show``

**Comment by oberon-manjaro** [comment]
Then when you use in luks_setup() and the next function ``return 1`` instead of ``0`` for cancel option like this:
```
DIALOG " $_LuksEncrypt " --menu "$_LuksCreateBody" 0 0 12 ${PARTITIONS} 2>${ANSWER} || return 0
```

WORKS !! :+1: 
Now next function will only be executed when ``$?`` of the one before is 0.

**Comment by oberon-manjaro** [comment]
Still not working properly. It's not exactly doing what it should, yet - need to check again ;)

**Comment by oberon-manjaro** [comment]
ah. actually the cancel funtion is working as it should now. just what confused me:
when i first tried i didn't have the disk partitioned and instead of giving an error message it just throws me back to prep_menu without any comment ;)
