### ISSUE TITLE
exit triggers check_mount()

### ISSUE THREAD

**Issue by oberon-manjaro** [oberon-manjaro/manjaro-architect#5]
why is this a problem?

**Comment by oberon-manjaro** [comment]
We just make sure that final_check()  makes sense at all and if it is even possible to write the log to target. You will only see an error when something really went wrong or when you haven't even done anything in the first place. Why else would nothing be mounted?

**Comment by Chrysostomus** [comment]
Almost all options in the preparation menu start with unmounting all partitions. So if if user visits one of these after installing, they get unnecessary error. Also if they just quit the installer straight away, they get error. Probably still better than calling final_check without partitions mounted... 

I think check_mount should not display error on exit, just disable final_check if partitions are not mounted.

**Comment by oberon-manjaro** [comment]
yes. makes sense. I'll change that.
