### ISSUE TITLE
disable openrc for Gnome and Budgie

### ISSUE THREAD

**Issue by oberon-manjaro** [oberon-manjaro/manjaro-architect#7]
@Ste74 could you let us know if you inted to remove the >openrc flags from those two menus? If not we'll figure out a less elegant way to exclude them from openrc in the installer.

**Comment by Ste74** [comment]
Yesterday i have removed from gnome via  https://github.com/manjaro/iso-profiles/commit/5137c78ce1da9be1652dd449652535636460652f
but maybe in my hands budgie not start but @Chrysostomus have success to install ?

**Comment by oberon-manjaro** [comment]
Ah, thank you @Ste74 ! I missed that :wink: 
I think @Chrysostomus aswell as eugen-b have tried Budgie with openrc without success, too ... :disappointed:

**Comment by Ste74** [comment]
Ok , when come back to home remove also in budgie :)

**Comment by Ste74** [comment]
Hi @oberon2007 removed in budgie too 😜

**Comment by oberon-manjaro** [comment]
Thanks a lot @Ste74 :smile:
